### ISSUE TITLE
Allow user to remove settings button on a web item

### ISSUE THREAD

**Issue by SuppliedOrange** [DenchiSoft/VTubeStudio#82]
![image](https://github.com/user-attachments/assets/78084fbd-c129-4efa-9625-7ad000aaa591)
![image](https://github.com/user-attachments/assets/8dfbf2f4-2a5a-456b-8fad-398fadf292a3)
<br>
Please allow the user to remove that settings button. Make it appear during hover or something. 
I use it as a speech bubble like this.

My alternative workaround was increasing the item size so that the button goes out of screen but it is inconvenient.

**Comment by DenchiSoft** [comment]
The settings buttons aren't actually shown in the capture if you use Spout2 (recommended), NDI or the Virtual Webcam. They only show up in Game Capture since that also captures the UI.

Regardless, there will be an option to make the gear invisible after a few seconds in the next update: https://trello.com/c/YEcQpnDg
